### ISSUE TITLE
【BUG】ishop与personalshop命名不符

### ISSUE THREAD

**Issue by ayakasuki** [shinianj/zhenxun_plugin_personalshop#1]
_init_.py这里load.piugin 后面还是ishop，这样加载成功插件是无效的，因为readme里建议插件文件夹命名为personalshop，应当默认改为personalshop，这边改了以后帮助菜单和调用才生效

**Comment by shinianj** [comment]
考虑过后两边都修改为zhenxun_plugin_personalshop了（据说仓库名会好写，顺便更新0.1版本了，以及我想说使用私商插件十分感谢）
