### ISSUE TITLE
关于增加商品失败的报错

### ISSUE THREAD

**Issue by imxianyu21** [shinianj/zhenxun_plugin_personalshop#2]
rt
![Screenshot_20220730-130600](https://user-images.githubusercontent.com/110275302/181875737-029363cb-fde8-4555-b3f7-4d13afbc3734.png)

**Comment by shinianj** [comment]
请更新最新版0.1

**Comment by imxianyu21** [comment]
以上代码均为今天中午下载下来的，均为0.1版本的内容，排除版本过旧的可能。

**Comment by shinianj** [comment]
是收到了上架失败的消息了对吧

**Comment by imxianyu21** [comment]
> 

是的，并且物品退还

**Comment by shinianj** [comment]
其他商品上架正常吗

**Comment by imxianyu21** [comment]
> 其他商品上架正常吗

没有可以正常上架的商品

**Comment by shinianj** [comment]
请问可以进入数据库看看吗，我想看看情况

**Comment by shinianj** [comment]
如果无法查看，请在create_shop.py 的第128行添加 print(f'{func_manager.check_send_success_message(name)}  {await func_text.add_goods_now(event.user_id,event.group_id,name,num,price)}') ，将执行截图给我看看

**Comment by imxianyu21** [comment]
> 请问可以进入数据库看看吗，我想看看情况

您需要哪些内容

**Comment by imxianyu21** [comment]
> 如果无法查看，请在create_shop.py 的第128行添加 print(f'{func_manager.check_send_success_message(name)} {await func_text.add_goods_now(event.user_id,event.group_id,name,num,price)}') ，将执行截图给我看看

我尝试一下

**Comment by shinianj** [comment]
> > 请问可以进入数据库看看吗，我想看看情况
> 
> 您需要哪些内容

表personalshop中的内容就行了

**Comment by imxianyu21** [comment]
> > 如果无法查看，请在create_shop.py 的第128行添加 print(f'{func_manager.check_send_success_message(name)} {await func_text.add_goods_now(event.user_id,event.group_id,name,num,price)}') ，将执行截图给我看看
> 
> 我尝试一下

![Uploading Screenshot_20220730-221626.png…]()
这样添加吗

**Comment by imxianyu21** [comment]
> 如果无法查看，请在create_shop.py 的第128行添加 print(f'{func_manager.check_send_success_message(name)} {await func_text.add_goods_now(event.user_id,event.group_id,name,num,price)}') ，将执行截图给我看看

![Screenshot_20220730-221626](https://user-images.githubusercontent.com/110275302/181918436-1a9517a4-ea89-44dd-94ce-9eb58d120148.png)
这样添加吗

**Comment by shinianj** [comment]
> > 如果无法查看，请在create_shop.py 的第128行添加 print(f'{func_manager.check_send_success_message(name)} {await func_text.add_goods_now(event.user_id,event.group_id,name,num,price)}') ，将执行截图给我看看
> 
> ![Screenshot_20220730-221626](https://user-images.githubusercontent.com/110275302/181918436-1a9517a4-ea89-44dd-94ce-9eb58d120148.png) 这样添加吗

是的

**Comment by shinianj** [comment]
我发现问题了，请问您的这个商品是可以通过使用道具直接使用的吗

**Comment by shinianj** [comment]
无法直接使用的商品无法直接上架（这是我的疏忽），现在更新了，可以上架使用了

**Comment by imxianyu21** [comment]
> 我发现问题了，请问您的这个商品是可以通过使用道具直接使用的吗

可以直接使用，只是没有效果（）

**Comment by shinianj** [comment]
![F~E5(_E@%RRMKR(~ZUAQN{5](https://user-images.githubusercontent.com/105840558/181919068-01366f38-12a3-419a-bb4d-4624beaa8f3a.png)
如果您这件商品是和电击枪这类，没有使用函数的商品，之前是无法上架的，之前上架只有好感卡那种，现在已经更新了，更新就可以使用了

**Comment by imxianyu21** [comment]
> ![F~E5(_E@%RRMKR(~ZUAQN{5](https://user-images.githubusercontent.com/105840558/181919068-01366f38-12a3-419a-bb4d-4624beaa8f3a.png) 如果您这件商品是和电击枪这类，没有使用函数的商品，之前是无法上架的，之前上架只有好感卡那种，现在已经更新了，更新就可以使用了

![IMG_20220730_223604](https://user-images.githubusercontent.com/110275302/181919173-755be901-ca00-44e6-ba2b-49fc0c18ffea.jpg)
现在已经可以正常使用了
