### ISSUE TITLE
请把系列插件打包进一个新建文件夹，“系列插件”是指哪些文件呢

### ISSUE THREAD

**Issue by Amoslzh** [shinianj/zhenxun_plugin_personalshop#3]
请把系列插件打包进一个新建文件夹，“系列插件”是指哪些文件呢
我直接把下载的文件夹放插件里了，导入也成功了，但发送指令没有任何反应，也没有报错
![OKLPV`06EQHV~U4FR90$XEM](https://user-images.githubusercontent.com/93984484/195249987-fc148d2a-7554-4568-ab6d-3ef768ddd508.png)
![5)F~}(S7))__LCZ%6N`(TYR](https://user-images.githubusercontent.com/93984484/195250001-1c19dc02-3ea3-481f-b332-4c68162b2412.png)

**Comment by Amoslzh** [comment]
![OKLPV`06EQHV~U4FR90$XEM](https://user-images.githubusercontent.com/93984484/195250053-50399003-9f13-4096-9af7-4013c5d4ea7e.png)

**Comment by shinianj** [comment]
![@{RR9` U3VO(L~X%(34{KWH](https://user-images.githubusercontent.com/105840558/195251712-880899b5-1f44-417b-8e66-e3fc7be3055c.png)
下载这些文件就行了

**Comment by shinianj** [comment]
原因估计是你的其他插件优先级过高，被优先获取了

**Comment by Amoslzh** [comment]
我找到问题了，你的readme写（建议命名为zhenxun_plugin_personal_shop)，然后你的_init_.py写的是nonebot.load_plugins("extensive_plugin/zhenxun_plugin_personalshop")，文件夹不对，没导入进来。

**Comment by shinianj** [comment]
哦，忘上传了
