### ISSUE TITLE
看不了别人商店有什么

### ISSUE THREAD

**Issue by 2497162852** [shinianj/zhenxun_plugin_personalshop#4]
![image](https://user-images.githubusercontent.com/33111780/201534610-fe9f2470-b26d-4c15-b8c5-8b478807fc09.png)

**Comment by 2497162852** [comment]
> ![image](https://user-images.githubusercontent.com/33111780/201534610-fe9f2470-b26d-4c15-b8c5-8b478807fc09.png)

![image](https://user-images.githubusercontent.com/33111780/201534711-e4e9d17b-4fc8-4fae-b2b1-4031be075f21.png)
跟这个有关吗

**Comment by shinianj** [comment]
你的艾特是不是复制过来的

**Comment by shinianj** [comment]
我中午的时候看一下

**Comment by shinianj** [comment]
能看看数据库的数据吗

**Comment by shinianj** [comment]
我本人不明白这个报错是如何出现的，情景究竟是怎么样的
